# Generated by Django 5.2.6 on 2025-10-04 09:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bài đăng tìm đối thủ', 'verbose_name_plural': 'Bài đăng tìm đối thủ'},
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Sân bóng chưa xác định', max_length=255, verbose_name='Địa điểm/Sân bóng'),
        ),
        migrations.AddField(
            model_name='post',
            name='match_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian thi đấu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đăng'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Chi tiết trận đấu'),
        ),
    ]
